Repository OpenChemistry/avogadrolibs, pull requests merged in 2021-07, with the labels that each got.

#640 New View => Apply Colors menu
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/applycolors/CMakeLists.txt
  avogadro/qtplugins/applycolors/applycolors.cpp
  avogadro/qtplugins/applycolors/applycolors.h
Labels: enhancement, rendering

#647 If a chain ID is missing / invalid, skip (to read non-standard PDB)
  avogadro/io/pdbformat.cpp
Labels: bug, file-format

#667 Refactor of JSON-based widgets
  avogadro/molequeue/inputgeneratorwidget.cpp
  avogadro/molequeue/inputgeneratorwidget.h
  avogadro/molequeue/inputgeneratorwidget.ui
  avogadro/qtgui/CMakeLists.txt
  avogadro/qtgui/interfacewidget.cpp
  avogadro/qtgui/interfacewidget.h
  avogadro/qtgui/jsonwidget.cpp
  avogadro/qtgui/jsonwidget.h
Labels: enhancement

#646 Add support for save/load residues and atom colors
  avogadro/core/molecule.h
  avogadro/core/residue.cpp
  avogadro/core/residue.h
  avogadro/io/cjsonformat.cpp
Labels: enhancement, file-format, rendering

#689 Fix #679 - incorrect PDB unit cells
  avogadro/io/pdbformat.cpp
Labels: bug

#660 All basic cartoons
  avogadro/core/atom.h
  avogadro/core/graph.cpp
  avogadro/core/graph.h
  avogadro/core/molecule.cpp
  avogadro/core/molecule.h
  avogadro/core/residue.cpp
  avogadro/core/residue.h
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/cartoons/CMakeLists.txt
  avogadro/qtplugins/cartoons/cartoons.cpp
  avogadro/qtplugins/cartoons/cartoons.h
  avogadro/rendering/CMakeLists.txt
  avogadro/rendering/beziergeometry.cpp
  avogadro/rendering/beziergeometry.h
  avogadro/rendering/bsplinegeometry.cpp
  avogadro/rendering/bsplinegeometry.h
  avogadro/rendering/cartoongeometry.cpp
  avogadro/rendering/cartoongeometry.h
  avogadro/rendering/curvegeometry.cpp
  avogadro/rendering/curvegeometry.h
  avogadro/rendering/scene.h
Labels: bio, enhancement, rendering

#690 When dragging to create a new atom, use starting coords
  avogadro/qtplugins/editor/editor.cpp
Labels: bug

#691 Fix "delete last atom" bug
  avogadro/qtplugins/copypaste/copypaste.cpp
Labels: bug

#700 Update render options
  avogadro/qtgui/CMakeLists.txt
  avogadro/qtgui/colorbutton.cpp
  avogadro/qtgui/colorbutton.h
  avogadro/qtplugins/ballandstick/ballandstick.cpp
  avogadro/qtplugins/cartoons/cartoons.cpp
  avogadro/qtplugins/crystal/crystalscene.cpp
  avogadro/qtplugins/crystal/crystalscene.h
  avogadro/qtplugins/wireframe/wireframe.cpp
  avogadro/qtplugins/wireframe/wireframe.h
Labels: enhancement, rendering
