Repository OpenChemistry/avogadrolibs, pull requests merged in 2021-08, with the labels that each got.

#716 Improve in cartoon display
  avogadro/core/residue.h
  avogadro/qtplugins/applycolors/applycolors.cpp
  avogadro/qtplugins/cartoons/cartoons.cpp
  avogadro/qtplugins/cartoons/cartoons.h
  avogadro/rendering/beziergeometry.cpp
  avogadro/rendering/beziergeometry.h
  avogadro/rendering/bsplinegeometry.cpp
  avogadro/rendering/bsplinegeometry.h
  avogadro/rendering/cartoongeometry.cpp
  avogadro/rendering/cartoongeometry.h
  avogadro/rendering/curvegeometry.cpp
  avogadro/rendering/curvegeometry.h
  avogadro/rendering/spheregeometry.cpp
  avogadro/rendering/spheregeometry.h
Labels: enhancement, rendering

#715 Labels
  avogadro/core/atom.h
  avogadro/core/molecule.cpp
  avogadro/core/molecule.h
  avogadro/io/cjsonformat.cpp
  avogadro/qtgui/rwmolecule.cpp
  avogadro/qtgui/rwmolecule.h
  avogadro/qtgui/rwmolecule_undo.h
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/label/CMakeLists.txt
  avogadro/qtplugins/label/label.cpp
  avogadro/qtplugins/label/label.h
Labels: enhancement, rendering

#722 Fix crash in CJSON reading file without labels
  avogadro/io/cjsonformat.cpp
Labels: bug

#723 Apply colors based on distance from atom 1
  avogadro/qtplugins/applycolors/applycolors.cpp
  avogadro/qtplugins/applycolors/applycolors.h
Labels: enhancement, rendering

#725 Update release-drafter template to include i18n for Weblate
  .github/release-drafter.yml
Labels: build

#724 Fix reading residues from CJSON including sec struct support
  avogadro/io/cjsonformat.cpp
Labels: bug

#726 Fix a crash with 1qlz (check new bonds have correct atom index)
  avogadro/io/mmtfformat.cpp
Labels: bug

#728 Fix odd behavior on 'Center'
  avogadro/qtplugins/resetview/resetview.cpp
Labels: bug

#729 Improve in selection tool
  avogadro/core/atom.h
  avogadro/core/molecule.h
  avogadro/qtgui/pluginlayermanager.cpp
  avogadro/qtgui/pluginlayermanager.h
  avogadro/qtgui/rwmolecule.cpp
  avogadro/qtgui/rwmolecule.h
  avogadro/qtgui/rwmolecule_undo.h
  avogadro/qtplugins/editor/editor.cpp
  avogadro/qtplugins/editor/editor.h
  avogadro/qtplugins/select/select.cpp
  avogadro/qtplugins/select/select.h
  avogadro/qtplugins/selectiontool/selectiontool.cpp
  avogadro/qtplugins/selectiontool/selectiontool.h
  avogadro/qtplugins/selectiontool/selectiontoolwidget.cpp
  avogadro/qtplugins/selectiontool/selectiontoolwidget.h
  avogadro/qtplugins/selectiontool/selectiontoolwidget.ui
Labels: enhancement

#736 Continue rendering cartoons even if residues aren't found
  avogadro/qtplugins/cartoons/cartoons.cpp
Labels: bug

#705 Fix reference axes menu item
  avogadro/qtplugins/overlayaxes/overlayaxes.cpp
  avogadro/qtplugins/overlayaxes/overlayaxes.h
Labels: bug, rendering

#738 Enable script formats like cclib to ask for bond perception on read
  avogadro/qtplugins/scriptfileformats/fileformatscript.cpp
  avogadro/qtplugins/scriptfileformats/fileformatscript.h
Labels: python

#743 Add "..." to all input generators to indicate opening a dialog
  avogadro/qtplugins/apbs/apbs.cpp
  avogadro/qtplugins/cp2kinput/cp2kinput.cpp
  avogadro/qtplugins/gamessinput/gamessinput.cpp
  avogadro/qtplugins/lammpsinput/lammpsinput.cpp
  avogadro/qtplugins/openmminput/openmminput.cpp
  avogadro/qtplugins/quantuminput/quantuminput.cpp
Labels: bug

#711 Initial property tables
  avogadro/core/angletools.h
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/propertytables/CMakeLists.txt
  avogadro/qtplugins/propertytables/propertymodel.cpp
  avogadro/qtplugins/propertytables/propertymodel.h
  avogadro/qtplugins/propertytables/propertytables.cpp
  avogadro/qtplugins/propertytables/propertytables.h
  avogadro/qtplugins/propertytables/propertyview.cpp
  avogadro/qtplugins/propertytables/propertyview.h
Labels: enhancement

#721 Translations update from Weblate
  i18n/hu.po
  i18n/sr.po
Labels: i18n

#739 Make sure to run tests in avogadrolibs
  .github/workflows/build_cmake.yml
  CMakeLists.txt
  avogadro/core/connectedgroup.cpp
  avogadro/core/molecule.cpp
  avogadro/qtgui/molecule.cpp
  avogadro/qtgui/molecule.h
  avogadro/qtgui/rwmolecule_undo.h
  tests/CMakeLists.txt
  tests/qtgui/CMakeLists.txt
  tests/qtgui/rwmoleculetest.cpp
Labels: build

#740 Add label editor to create custom labels
  avogadro/qtplugins/label/CMakeLists.txt
  avogadro/qtplugins/label/label.cpp
  avogadro/qtplugins/label/label.h
  avogadro/qtplugins/label/label.qrc
  avogadro/qtplugins/label/labeleditor.cpp
  avogadro/qtplugins/label/labeleditor.h
  avogadro/qtplugins/label/labeltool.png
  avogadro/qtplugins/label/labeltool@2x.png
Labels: enhancement, rendering
