Repository OpenChemistry/avogadrolibs, pull requests merged in 2022-03, with the labels that each got.

#831 Formal charges
  avogadro/core/molecule.h
  avogadro/io/cjsonformat.cpp
  avogadro/io/cmlformat.cpp
  avogadro/io/mdlformat.cpp
  avogadro/io/mdlformat.h
  avogadro/io/pdbformat.cpp
  avogadro/io/pdbformat.h
  avogadro/qtgui/rwmolecule.cpp
Labels: enhancement

#839 Add formal charge to atom property tables
  avogadro/qtplugins/propertytables/propertymodel.cpp
  avogadro/qtplugins/propertytables/propertymodel.h
Labels: enhancement

#848 Fix #827 - reading generic file formats with Open Babel
  avogadro/qtplugins/openbabel/openbabel.cpp
Labels: bug

#847 Try to fix the broken wheels. Windows complains about std::array
  avogadro/core/molecule.cpp
  avogadro/io/mdlformat.cpp
  avogadro/io/pdbformat.cpp
Labels: build
