Repository OpenChemistry/avogadrolibs, pull requests merged in 2022-07, with the labels that each got.

#991 More work to debug m1 notarization
  .github/workflows/build_m1.yml
Labels: build

#998 Add Python charge scripts. First example xtb GFN2 charges
  avogadro/calc/chargemodel.cpp
  avogadro/calc/chargemodel.h
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/scriptcharges/CMakeLists.txt
  avogadro/qtplugins/scriptcharges/chargeScripts/xtb.py
  avogadro/qtplugins/scriptcharges/scriptchargemodel.cpp
  avogadro/qtplugins/scriptcharges/scriptchargemodel.h
  avogadro/qtplugins/scriptcharges/scriptcharges.cpp
  avogadro/qtplugins/scriptcharges/scriptcharges.h
Labels: enhancement

#1002 Use single-point calculation for AM1-BCC with Antechamber
  avogadro/qtplugins/scriptcharges/chargeScripts/antechamber.py
Labels: bug

#1007 More clang-tidy esp. const fixes
  .clang-tidy
  .clang-tidy-ignore
  avogadro/calc/chargemanager.cpp
  avogadro/calc/chargemanager.h
  avogadro/calc/chargemodel.h
  avogadro/calc/defaultmodel.cpp
  avogadro/calc/defaultmodel.h
  avogadro/core/graph.cpp
  avogadro/core/graph.h
  avogadro/core/molecule.cpp
  avogadro/core/molecule.h
  avogadro/core/neighborperceiver.cpp
  avogadro/core/neighborperceiver.h
  avogadro/core/residue.cpp
  avogadro/core/residue.h
  avogadro/core/secondarystructure.cpp
  avogadro/core/slaterset.cpp
  avogadro/io/cjsonformat.cpp
  avogadro/molequeue/inputgeneratorwidget.cpp
  avogadro/qtgui/fileformatdialog.cpp
  avogadro/qtgui/fileformatdialog.h
  avogadro/qtgui/layermodel.cpp
  avogadro/qtgui/layermodel.h
  avogadro/qtplugins/insertfragment/insertfragmentdialog.cpp
  avogadro/qtplugins/insertfragment/insertfragmentdialog.h
  avogadro/qtplugins/label/labeleditor.cpp
  avogadro/qtplugins/openbabel/obcharges.cpp
  avogadro/qtplugins/openbabel/obcharges.h
  avogadro/qtplugins/plugindownloader/zipextracter.cpp
  avogadro/qtplugins/pluginfactory.h
  avogadro/qtplugins/qtaim/qtaimcriticalpointlocator.cpp
  avogadro/qtplugins/qtaim/qtaimwavefunctionevaluator.cpp
  avogadro/qtplugins/qtaim/qtaimwavefunctionevaluator.h
  avogadro/qtplugins/scriptcharges/scriptchargemodel.cpp
  avogadro/qtplugins/scriptcharges/scriptchargemodel.h
  avogadro/qtplugins/select/select.cpp
  avogadro/qtplugins/surfaces/gaussiansetconcurrent.cpp
  avogadro/qtplugins/surfaces/slatersetconcurrent.cpp
  avogadro/quantumio/nwchemjson.cpp
  avogadro/rendering/cartoongeometry.cpp
  avogadro/rendering/povrayvisitor.cpp
  cmake/avogadroplugin.cpp.in
Labels: build

#913 Enable editing of some properties
  avogadro/qtplugins/propertytables/propertymodel.cpp
  avogadro/qtplugins/propertytables/propertymodel.h
Labels: enhancement

#1011 Add select water, enlarge selection and shrink selection
  avogadro/qtplugins/select/select.cpp
  avogadro/qtplugins/select/select.h
Labels: enhancement

#1012 Implement support for Turbomole coord format (also used by xtb)
  avogadro/io/CMakeLists.txt
  avogadro/io/fileformatmanager.cpp
  avogadro/io/turbomoleformat.cpp
  avogadro/io/turbomoleformat.h
Labels: enhancement

#1022 Make sure to also select isolated "O" as part of HOH residues
  avogadro/qtplugins/select/select.cpp
Labels: bug

#1021 Initial salt bridge implementation
  avogadro/qtplugins/closecontacts/closecontacts.cpp
Labels: enhancement, rendering

#1023 Add "select backbone" and "select sidechain" commands
  avogadro/core/residue.cpp
  avogadro/core/residue.h
  avogadro/qtplugins/select/select.cpp
  avogadro/qtplugins/select/select.h
Labels: enhancement

#1029 No longer bundle the "scale" example script - these can be downloaded
  avogadro/qtplugins/commandscripts/CMakeLists.txt
  avogadro/qtplugins/commandscripts/scripts/scale.py
Labels: bug

#1028 Fix some menu priorities for file import/export
  avogadro/qtplugins/fetchpdb/fetchpdb.cpp
  avogadro/qtplugins/insertfragment/insertfragment.cpp
  avogadro/qtplugins/networkdatabases/networkdatabases.cpp
Labels: bug

#1030 Make sure to process events while rendering an animation
  avogadro/qtplugins/playertool/playertool.cpp
Labels: bug

#1033 Fix two minor input generator bugs
  avogadro/molequeue/inputgeneratorwidget.cpp
Labels: bug

#1038 Fix crash when layer names are translated (hu_HU right now)
  avogadro/qtgui/layermodel.cpp
Labels: bug, crash

#1037 Fix input generators (and other scripts) with translation
  avogadro/qtgui/jsonwidget.cpp
  avogadro/qtgui/jsonwidget.h
Labels: bug

#1047 Add AltLoc support to PDB importer
  avogadro/io/pdbformat.cpp
Labels: bug

#1050 Fix CMake error with missing conf.py.in [skip-ci]
  docs/CMakeLists.txt
Labels: build

#1054 Tweak for M1 5.15.5 from homebrew [skip-ci]
  .github/workflows/build_m1.yml
Labels: build

#1058 Initial support for total charge and spin through CJSON.
  avogadro/core/molecule.cpp
  avogadro/core/molecule.h
  avogadro/io/cjsonformat.cpp
Labels: enhancement

#1061 Optimize NeighborPerceiver
  avogadro/core/neighborperceiver.cpp
  avogadro/core/neighborperceiver.h
Labels: speed

#1063 Fix bug selecting incorrect angle and torsion atoms
  avogadro/qtplugins/propertytables/propertyview.cpp
Labels: bug

#1062 Add default spin multiplicity methods
  avogadro/core/molecule.cpp
  avogadro/core/molecule.h
  avogadro/io/cjsonformat.cpp
  avogadro/qtgui/interfacescript.cpp
  avogadro/quantumio/gamessus.cpp
  avogadro/quantumio/gaussianfchk.cpp
  avogadro/quantumio/gaussianfchk.h
Labels: enhancement

#1065 Avoid using QWheelEvent::pixelDelta() on X11
  avogadro/qtplugins/navigator/navigator.cpp
Labels: bug

#1068 Move arc and quad mesh and linestrip convenience classes
  avogadro/qtplugins/bondcentrictool/bondcentrictool.cpp
  avogadro/qtplugins/symmetry/symmetryscene.cpp
  avogadro/rendering/CMakeLists.txt
  avogadro/rendering/arcsector.cpp
  avogadro/rendering/arcsector.h
  avogadro/rendering/arcstrip.cpp
  avogadro/rendering/arcstrip.h
  avogadro/rendering/quad.cpp
  avogadro/rendering/quad.h
  avogadro/rendering/quadoutline.cpp
  avogadro/rendering/quadoutline.h
Labels: rendering
