Repository OpenChemistry/avogadrolibs, pull requests merged in 2022-06, with the labels that each got.

#891 Translations update from Hosted Weblate
  i18n/af.po
  i18n/ar.po
  i18n/bg.po
  i18n/bs.po
  i18n/ca.po
  i18n/ca@valencia.po
  i18n/cs.po
  i18n/da.po
  i18n/de.po
  i18n/el.po
  i18n/en_AU.po
  i18n/en_CA.po
  i18n/en_GB.po
  i18n/eo.po
  i18n/es.po
  i18n/et.po
  i18n/eu.po
  i18n/fa.po
  i18n/fi.po
  i18n/fr.po
  i18n/fr_CA.po
  i18n/gl.po
  i18n/he.po
  i18n/hi.po
  i18n/hr.po
  i18n/hu.po
  i18n/id.po
  i18n/it.po
  i18n/ja.po
  i18n/ka.po
  i18n/kn.po
  i18n/ko.po
  i18n/ms.po
  i18n/nb.po
  i18n/nl.po
  i18n/oc.po
  i18n/pl.po
  i18n/pt_BR.po
  i18n/ro.po
  i18n/ru.po
  i18n/sa.po
  i18n/sk.po
  i18n/sl.po
  i18n/sq.po
  i18n/sr.po
  i18n/sv.po
  i18n/ta.po
  i18n/te.po
  i18n/th.po
  i18n/tr.po
  i18n/ug.po
  i18n/uk.po
  i18n/vi.po
  i18n/zh_CN.po
  i18n/zh_TW.po
Labels: i18n

#927 Fix error when notarizing Mac DMG - use the right working dir
  .github/workflows/build_cmake.yml
Labels: build

#926 Implement basic hydrogen bonds
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/closecontacts/closecontacts.cpp
  avogadro/qtplugins/noncovalent/CMakeLists.txt
  avogadro/qtplugins/noncovalent/noncovalent.cpp
  avogadro/qtplugins/noncovalent/noncovalent.h
Labels: rendering

#937 Check for Open Babel CJSON support: use it if available
  avogadro/qtplugins/openbabel/obfileformat.cpp
  avogadro/qtplugins/openbabel/obfileformat.h
  avogadro/qtplugins/openbabel/obforcefielddialog.cpp
  avogadro/qtplugins/openbabel/obforcefielddialog.h
  avogadro/qtplugins/openbabel/obprocess.cpp
  avogadro/qtplugins/openbabel/obprocess.h
  avogadro/qtplugins/openbabel/openbabel.cpp
  avogadro/qtplugins/openbabel/openbabel.h
Labels: enhancement

#938 Rename intensities to IR and add Raman intensities if available
  avogadro/core/molecule.cpp
  avogadro/core/molecule.h
  avogadro/io/cjsonformat.cpp
  avogadro/qtplugins/spectra/vibrationmodel.cpp
  avogadro/qtplugins/spectra/vibrationmodel.h
  avogadro/quantumio/nwchemjson.cpp
  avogadro/quantumio/nwchemlog.cpp
Labels: enhancement

#941 Start to filter Codacy warnings (e.g., remove MISRA)
  .github/workflows/codacy.yml
  scripts/github-actions/filter_sarif.py
Labels: build

#939 Make use of angle tolerance for hole detection
  avogadro/core/bond.h
  avogadro/qtplugins/noncovalent/noncovalent.cpp
Labels: enhancement

#940 Move some HydrogenTools code into AtomUtilities
  avogadro/core/CMakeLists.txt
  avogadro/core/atomutilities.cpp
  avogadro/core/atomutilities.h
  avogadro/qtgui/hydrogentools.cpp
  avogadro/qtgui/hydrogentools.h
Labels: build

#934 Add line widths to the non-covalent / h-bond rendering
  avogadro/qtplugins/noncovalent/noncovalent.cpp
  avogadro/qtplugins/noncovalent/noncovalent.h
Labels: enhancement, rendering

#947 Enable GL_LINE_SMOOTH in DashedLineGeometry
  avogadro/rendering/dashedlinegeometry.cpp
Labels: rendering

#946 Add electron pair angle check for hydrogen bonds
  avogadro/core/atomutilities.cpp
  avogadro/core/atomutilities.h
  avogadro/qtplugins/noncovalent/noncovalent.cpp
Labels: enhancement, rendering

#928 Translations update from Hosted Weblate
  i18n/af.po
  i18n/ar.po
  i18n/bg.po
  i18n/bs.po
  i18n/ca.po
  i18n/ca@valencia.po
  i18n/cs.po
  i18n/da.po
  i18n/de.po
  i18n/el.po
  i18n/en_AU.po
  i18n/en_CA.po
  i18n/en_GB.po
  i18n/eo.po
  i18n/es.po
  i18n/et.po
  i18n/eu.po
  i18n/fa.po
  i18n/fi.po
  i18n/fr.po
  i18n/fr_CA.po
  i18n/gl.po
  i18n/he.po
  i18n/hi.po
  i18n/hr.po
  i18n/hu.po
  i18n/id.po
  i18n/it.po
  i18n/ja.po
  i18n/ka.po
  i18n/kn.po
  i18n/ko.po
  i18n/ms.po
  i18n/nb.po
  i18n/nl.po
  i18n/oc.po
  i18n/pl.po
  i18n/pt_BR.po
  i18n/ro.po
  i18n/ru.po
  i18n/sa.po
  i18n/sk.po
  i18n/sl.po
  i18n/sq.po
  i18n/sr.po
  i18n/sv.po
  i18n/ta.po
  i18n/te.po
  i18n/th.po
  i18n/tr.po
  i18n/ug.po
  i18n/uk.po
  i18n/vi.po
  i18n/zh_CN.po
  i18n/zh_TW.po
Labels: i18n

#948 Make sure to translate menu paths for Python scripts.
  avogadro/qtplugins/commandscripts/command.cpp
Labels: i18n

#949 Add halogen and chalcogen bonds, tune parameters
  avogadro/qtplugins/closecontacts/closecontacts.cpp
  avogadro/qtplugins/noncovalent/noncovalent.cpp
  avogadro/qtplugins/noncovalent/noncovalent.h
Labels: enhancement

#956 Fix several i18n problems
  avogadro/qtgui/layermodel.cpp
  avogadro/qtplugins/cartoons/cartoons.h
  avogadro/qtplugins/closecontacts/closecontacts.h
  avogadro/qtplugins/licorice/licorice.h
  avogadro/qtplugins/molecularproperties/molecularproperties.cpp
  avogadro/qtplugins/molecularproperties/molecularproperties.h
  avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.cpp
  avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.h
  avogadro/qtplugins/wireframe/wireframe.h
Labels: i18n

#959 Fix errors in pt translation file [skip ci]
  i18n/pt.po
Labels: i18n

#966 Add missing acceptors and make distance relative (non-covalent)
  avogadro/qtplugins/noncovalent/noncovalent.cpp
Labels: enhancement

#970 Initial electrostatics framework
  avogadro/CMakeLists.txt
  avogadro/calc/CMakeLists.txt
  avogadro/calc/chargemanager.cpp
  avogadro/calc/chargemanager.h
  avogadro/calc/chargemodel.cpp
  avogadro/calc/chargemodel.h
  avogadro/calc/defaultmodel.cpp
  avogadro/calc/defaultmodel.h
  avogadro/core/elementdata.h
  avogadro/core/elements.h
  avogadro/core/molecule.cpp
  avogadro/core/molecule.h
  avogadro/core/variantmap.h
  avogadro/io/cjsonformat.cpp
  avogadro/qtplugins/propertytables/propertymodel.cpp
  avogadro/qtplugins/propertytables/propertymodel.h
Labels: enhancement

#972 Implement Solvent Excluded Surfaces
  avogadro/core/cube.cpp
  avogadro/core/cube.h
  avogadro/qtplugins/surfaces/surfacedialog.cpp
  avogadro/qtplugins/surfaces/surfaces.cpp
  avogadro/qtplugins/surfaces/surfaces.h
Labels: enhancement

#977 Bump Qt version to 5.15.2 (LTS) now that VTK-9 is working
  .github/workflows/add_artifact_urls.yml
  .github/workflows/build_cmake.yml
  .github/workflows/build_m1.yml
Labels: build

#976 Add "Automatic" resolution, smoothing pass UI, optimization
  avogadro/core/mesh.cpp
  avogadro/qtplugins/surfaces/surfacedialog.cpp
  avogadro/qtplugins/surfaces/surfacedialog.h
  avogadro/qtplugins/surfaces/surfacedialog.ui
  avogadro/qtplugins/surfaces/surfaces.cpp
  avogadro/qtplugins/surfaces/surfaces.h
Labels: enhancement

#980 Fix incorrect hydrogen geometries
  avogadro/qtgui/hydrogentools.cpp
Labels: bug

#981 Fix notarization for Mac M1 builds
  .github/workflows/build_m1.yml
Labels: build

#982 Add arrow key navigation of the periodic table
  avogadro/qtgui/periodictableview.cpp
Labels: enhancement

#985 Optimize mesh smoothing
  avogadro/core/mesh.cpp
Labels: speed
