Repository OpenChemistry/avogadrolibs, pull requests merged in 2022-04, with the labels that each got.

#861 Try using Windows 2019 to build wheels
  .github/workflows/build_wheels.yml
Labels: build

#832 Bond graph optimization
  avogadro/core/connectedgroup.cpp
  avogadro/core/graph.cpp
  avogadro/core/graph.h
  avogadro/core/molecule.cpp
  avogadro/core/molecule.h
  avogadro/qtgui/rwmolecule.h
Labels: enhancement

#867 Try to install Eigen on Windows and Ubuntu
  scripts/github-actions/install.sh
Labels: build

#862 Implement close contact perception logic
  avogadro/core/CMakeLists.txt
  avogadro/core/molecule.cpp
  avogadro/core/neighborperceiver.cpp
  avogadro/core/neighborperceiver.h
Labels: enhancement

#868 Add plugin to focus or unfocus selection
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/focus/CMakeLists.txt
  avogadro/qtplugins/focus/focus.cpp
  avogadro/qtplugins/focus/focus.h
  avogadro/qtplugins/navigator/navigator.cpp
  avogadro/rendering/camera.h
  avogadro/rendering/glrenderer.cpp
Labels: enhancement

#855 OpenGL: Detaching and deleting shaders/programs on updates
  avogadro/rendering/cylindergeometry.cpp
  avogadro/rendering/linestripgeometry.cpp
  avogadro/rendering/shaderprogram.cpp
  avogadro/rendering/spheregeometry.cpp
  avogadro/rendering/textlabelbase.cpp
Labels: bug, rendering

#873 Write Gaussian cube files
  avogadro/quantumio/gaussiancube.cpp
  avogadro/quantumio/gaussiancube.h
Labels: enhancement

#875 Import and retain space group information
  avogadro/core/molecule.cpp
  avogadro/core/spacegroups.cpp
  avogadro/core/spacegroups.h
  avogadro/io/cmlformat.cpp
  avogadro/io/cmlformat.h
  avogadro/io/mmtfformat.cpp
  avogadro/qtplugins/spacegroup/spacegroup.cpp
  avogadro/qtplugins/spacegroup/spacegroup.h
Labels: enhancement

#877 Add an initial config widget to set colors and opacity
  avogadro/qtplugins/meshes/meshes.cpp
  avogadro/qtplugins/meshes/meshes.h
Labels: enhancement, rendering

#880 Tweak the mesh lighting .. now lights "from the top"
  avogadro/rendering/CMakeLists.txt
  avogadro/rendering/mesh_opaque_fs.glsl
  avogadro/rendering/meshgeometry.cpp
  avogadro/rendering/meshgeometry.h
Labels: rendering
