Repository OpenChemistry/avogadrolibs, pull requests merged in 2022-08, with the labels that each got.

#1075 Initial template tool
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/templatetool/CMakeLists.txt
  avogadro/qtplugins/templatetool/centers/1-lin.cjson
  avogadro/qtplugins/templatetool/centers/1-lin.png
  avogadro/qtplugins/templatetool/centers/1-lin.svg
  avogadro/qtplugins/templatetool/centers/2-lin.cjson
  avogadro/qtplugins/templatetool/centers/2-lin.png
  avogadro/qtplugins/templatetool/centers/2-lin.svg
  avogadro/qtplugins/templatetool/centers/3-tpl.cjson
  avogadro/qtplugins/templatetool/centers/3-tpl.png
  avogadro/qtplugins/templatetool/centers/3-tpl.svg
  avogadro/qtplugins/templatetool/centers/4-sqp.cjson
  avogadro/qtplugins/templatetool/centers/4-sqp.png
  avogadro/qtplugins/templatetool/centers/4-sqp.svg
  avogadro/qtplugins/templatetool/centers/4-tet.cjson
  avogadro/qtplugins/templatetool/centers/4-tet.png
  avogadro/qtplugins/templatetool/centers/4-tet.svg
  avogadro/qtplugins/templatetool/centers/5-spy.cjson
  avogadro/qtplugins/templatetool/centers/5-spy.png
  avogadro/qtplugins/templatetool/centers/5-spy.svg
  avogadro/qtplugins/templatetool/centers/5-tbp.cjson
  avogadro/qtplugins/templatetool/centers/5-tbp.png
  avogadro/qtplugins/templatetool/centers/5-tbp.svg
  avogadro/qtplugins/templatetool/centers/6-oct.cjson
  avogadro/qtplugins/templatetool/centers/6-oct.png
  avogadro/qtplugins/templatetool/centers/6-oct.svg
  avogadro/qtplugins/templatetool/centers/6-tpr.cjson
  avogadro/qtplugins/templatetool/centers/6-tpr.png
  avogadro/qtplugins/templatetool/centers/6-tpr.svg
  avogadro/qtplugins/templatetool/centers/7-pbp.cjson
  avogadro/qtplugins/templatetool/centers/7-pbp.png
  avogadro/qtplugins/templatetool/centers/7-pbp.svg
  avogadro/qtplugins/templatetool/centers/8-sqa.cjson
  avogadro/qtplugins/templatetool/centers/8-sqa.png
  avogadro/qtplugins/templatetool/centers/8-sqa.svg
  avogadro/qtplugins/templatetool/ligands/ammine.cjson
  avogadro/qtplugins/templatetool/ligands/aqua.cjson
  avogadro/qtplugins/templatetool/ligands/carbonyl.cjson
  avogadro/qtplugins/templatetool/ligands/ethyl.cjson
  avogadro/qtplugins/templatetool/ligands/isopropyl.cjson
  avogadro/qtplugins/templatetool/ligands/methyl.cjson
  avogadro/qtplugins/templatetool/ligands/phosphine.cjson
  avogadro/qtplugins/templatetool/ligands/propyl.cjson
  avogadro/qtplugins/templatetool/ligands/t-butyl.cjson
  avogadro/qtplugins/templatetool/ligands/thiol.cjson
  avogadro/qtplugins/templatetool/template.png
  avogadro/qtplugins/templatetool/template.qrc
  avogadro/qtplugins/templatetool/template@2x.png
  avogadro/qtplugins/templatetool/templatetool.cpp
  avogadro/qtplugins/templatetool/templatetool.h
  avogadro/qtplugins/templatetool/templatetoolwidget.cpp
  avogadro/qtplugins/templatetool/templatetoolwidget.h
  avogadro/qtplugins/templatetool/templatetoolwidget.ui
Labels: enhancement

#1076 Add commands for centroid and center-of-mass atoms
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/centroid/CMakeLists.txt
  avogadro/qtplugins/centroid/centroid.cpp
  avogadro/qtplugins/centroid/centroid.h
Labels: enhancement

#1077 Fix linking to calc module
  avogadro/qtplugins/surfaces/CMakeLists.txt
Labels: build

#1078 Fix some Edit and Build menu priorities
  avogadro/qtplugins/bonding/bonding.cpp
  avogadro/qtplugins/centroid/centroid.cpp
  avogadro/qtplugins/coordinateeditor/coordinateeditor.cpp
  avogadro/qtplugins/copypaste/copypaste.cpp
  avogadro/qtplugins/hydrogens/hydrogens.cpp
  avogadro/qtplugins/insertdna/insertdna.cpp
  avogadro/qtplugins/insertfragment/insertfragment.cpp
  avogadro/qtplugins/lineformatinput/lineformatinput.cpp
Labels: bug

#1079 Fix properties menu priorities
  avogadro/qtplugins/molecularproperties/molecularproperties.cpp
  avogadro/qtplugins/propertytables/propertytables.cpp
  avogadro/qtplugins/symmetry/symmetry.cpp
Labels: bug

#1080 Add support for polydentate ligand templates
  avogadro/qtplugins/templatetool/ligands/1-ammine.cjson
  avogadro/qtplugins/templatetool/ligands/1-aqua.cjson
  avogadro/qtplugins/templatetool/ligands/1-carbonyl.cjson
  avogadro/qtplugins/templatetool/ligands/1-ethyl.cjson
  avogadro/qtplugins/templatetool/ligands/1-isopropyl.cjson
  avogadro/qtplugins/templatetool/ligands/1-methyl.cjson
  avogadro/qtplugins/templatetool/ligands/1-phosphine.cjson
  avogadro/qtplugins/templatetool/ligands/1-propyl.cjson
  avogadro/qtplugins/templatetool/ligands/1-t-butyl.cjson
  avogadro/qtplugins/templatetool/ligands/1-thiol.cjson
  avogadro/qtplugins/templatetool/ligands/2-bipyridine.cjson
  avogadro/qtplugins/templatetool/ligands/2-ethylenediamine.cjson
  avogadro/qtplugins/templatetool/ligands/3-terpyridine.cjson
  avogadro/qtplugins/templatetool/ligands/4-phthalocyanine.cjson
  avogadro/qtplugins/templatetool/ligands/4-porphin.cjson
  avogadro/qtplugins/templatetool/template.qrc
  avogadro/qtplugins/templatetool/templatetool.cpp
  avogadro/qtplugins/templatetool/templatetoolwidget.cpp
  avogadro/qtplugins/templatetool/templatetoolwidget.h
  avogadro/qtplugins/templatetool/templatetoolwidget.ui
Labels: enhancement

#1083 Add Dependabot update checks for GitHub actions
  .github/dependabot.yml
Labels: build

#1091 Fix bug to allow editing atom formal charges
  avogadro/qtplugins/propertytables/propertymodel.cpp
Labels: bug

#1096 Perceive bond orders
  avogadro/core/elementdata.h
  avogadro/core/elements.cpp
  avogadro/core/elements.h
  avogadro/core/molecule.cpp
  avogadro/core/molecule.h
  avogadro/io/turbomoleformat.cpp
  avogadro/io/xyzformat.cpp
  avogadro/qtplugins/bonding/bonding.cpp
  avogadro/qtplugins/bonding/bonding.h
  avogadro/quantumio/gamessus.cpp
  avogadro/quantumio/gaussiancube.cpp
  avogadro/quantumio/gaussianfchk.cpp
  avogadro/quantumio/molden.cpp
  avogadro/quantumio/mopacaux.cpp
  avogadro/quantumio/nwchemjson.cpp
  avogadro/quantumio/nwchemlog.cpp
Labels: enhancement

#1097 Fix template tool, add more ligands and preview
  avogadro/qtplugins/label/labeleditor.h
  avogadro/qtplugins/templatetool/ligands/1-ammine.png
  avogadro/qtplugins/templatetool/ligands/1-aqua.png
  avogadro/qtplugins/templatetool/ligands/1-carbonyl.png
  avogadro/qtplugins/templatetool/ligands/1-cyano.cjson
  avogadro/qtplugins/templatetool/ligands/1-cyano.png
  avogadro/qtplugins/templatetool/ligands/1-ethyl.png
  avogadro/qtplugins/templatetool/ligands/1-isopropyl.png
  avogadro/qtplugins/templatetool/ligands/1-methyl.png
  avogadro/qtplugins/templatetool/ligands/1-phosphine.png
  avogadro/qtplugins/templatetool/ligands/1-propyl.png
  avogadro/qtplugins/templatetool/ligands/1-pyridyl.cjson
  avogadro/qtplugins/templatetool/ligands/1-pyridyl.png
  avogadro/qtplugins/templatetool/ligands/1-t-butyl.png
  avogadro/qtplugins/templatetool/ligands/1-thiol.png
  avogadro/qtplugins/templatetool/ligands/2-acetylacetonate.cjson
  avogadro/qtplugins/templatetool/ligands/2-acetylacetonate.png
  avogadro/qtplugins/templatetool/ligands/2-bipyridine.png
  avogadro/qtplugins/templatetool/ligands/2-ethylenediamine.png
  avogadro/qtplugins/templatetool/ligands/3-terpyridine.png
  avogadro/qtplugins/templatetool/ligands/4-phthalocyanine.png
  avogadro/qtplugins/templatetool/ligands/4-porphin.png
  avogadro/qtplugins/templatetool/ligands/4-salen.cjson
  avogadro/qtplugins/templatetool/ligands/4-salen.png
  avogadro/qtplugins/templatetool/ligands/6-edta.cjson
  avogadro/qtplugins/templatetool/ligands/6-edta.png
  avogadro/qtplugins/templatetool/ligands/amide.cjson
  avogadro/qtplugins/templatetool/ligands/amide.png
  avogadro/qtplugins/templatetool/ligands/carboxylate.cjson
  avogadro/qtplugins/templatetool/ligands/carboxylate.png
  avogadro/qtplugins/templatetool/ligands/ester.cjson
  avogadro/qtplugins/templatetool/ligands/ester.png
  avogadro/qtplugins/templatetool/ligands/nitro.cjson
  avogadro/qtplugins/templatetool/ligands/nitro.png
  avogadro/qtplugins/templatetool/ligands/sulfonate.cjson
  avogadro/qtplugins/templatetool/ligands/sulfonate.png
  avogadro/qtplugins/templatetool/ligands/η2-ethylene.cjson
  avogadro/qtplugins/templatetool/ligands/η2-ethylene.png
  avogadro/qtplugins/templatetool/ligands/η5-cyclopentyl.cjson
  avogadro/qtplugins/templatetool/ligands/η5-cyclopentyl.png
  avogadro/qtplugins/templatetool/ligands/η6-benzene.cjson
  avogadro/qtplugins/templatetool/ligands/η6-benzene.png
  avogadro/qtplugins/templatetool/template.qrc
  avogadro/qtplugins/templatetool/templatetool.cpp
  avogadro/qtplugins/templatetool/templatetoolwidget.cpp
  avogadro/qtplugins/templatetool/templatetoolwidget.h
  avogadro/qtplugins/templatetool/templatetoolwidget.ui
Labels: enhancement

#1102 Fix to use "eta" filenames for "C" locale
  avogadro/qtplugins/templatetool/ligands/phenyl.cjson
  avogadro/qtplugins/templatetool/ligands/phenyl.png
  avogadro/qtplugins/templatetool/template.qrc
  avogadro/qtplugins/templatetool/templatetoolwidget.cpp
Labels: build

#1100 Enable Yaehmop commands - enable if in PATH
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/yaehmop/yaehmop.cpp
  avogadro/qtplugins/yaehmop/yaehmop.h
  avogadro/qtplugins/yaehmop/yaehmopout.cpp
Labels: enhancement

#1103 Fetch molecule names from PubChem PUG interface
  avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.cpp
  avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.h
  avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.ui
Labels: enhancement

#1108 Don't "apply layer" if layer is already zero
  .github/workflows/misspell-fixer.yml
  avogadro/qtplugins/importpqr/pqrrequest.cpp
  avogadro/qtplugins/importpqr/pqrrequest.h
  avogadro/qtplugins/openmminput/openmminputdialog.cpp
  avogadro/qtplugins/selectiontool/selectiontool.cpp
Labels: bug

#1112 Make sure to add / adjust valence in the correct order
  avogadro/qtgui/rwmolecule.cpp
  avogadro/qtplugins/editor/editor.cpp
Labels: bug

#1113 Update to latest version of install-qt-action
  .github/workflows/build_cmake.yml
Labels: build

#1119 Add a copy button for molecular properties
  avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.cpp
  avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.h
  avogadro/qtplugins/molecularproperties/molecularpropertiesdialog.ui
Labels: enhancement

#1126 Turn off VTK builds for AppImage, Mac, Windows for now
  .github/workflows/build_cmake.yml
  .github/workflows/build_m1.yml
Labels: build

#1122 Translations update from Hosted Weblate
  i18n/af.po
  i18n/ar.po
  i18n/bg.po
  i18n/bs.po
  i18n/ca.po
  i18n/ca@valencia.po
  i18n/cs.po
  i18n/da.po
  i18n/de.po
  i18n/el.po
  i18n/en_AU.po
  i18n/en_CA.po
  i18n/en_GB.po
  i18n/eo.po
  i18n/es.po
  i18n/et.po
  i18n/eu.po
  i18n/fa.po
  i18n/fi.po
  i18n/fr.po
  i18n/fr_CA.po
  i18n/gl.po
  i18n/he.po
  i18n/hi.po
  i18n/hr.po
  i18n/hu.po
  i18n/id.po
  i18n/it.po
  i18n/ja.po
  i18n/ka.po
  i18n/kn.po
  i18n/ko.po
  i18n/ms.po
  i18n/nb.po
  i18n/nl.po
  i18n/oc.po
  i18n/pl.po
  i18n/pt.po
  i18n/pt_BR.po
  i18n/ro.po
  i18n/ru.po
  i18n/sa.po
  i18n/sk.po
  i18n/sl.po
  i18n/sq.po
  i18n/sr.po
  i18n/sv.po
  i18n/ta.po
  i18n/te.po
  i18n/th.po
  i18n/tr.po
  i18n/ug.po
  i18n/uk.po
  i18n/vi.po
  i18n/zh_CN.po
  i18n/zh_TW.po
Labels: i18n

#1131 Pick a contrasting color (vs. the background) for the text
  avogadro/qtplugins/editor/editor.cpp
Labels: enhancement

#1132 Catch exceptions thrown by mmtf:decode
  avogadro/io/mmtfformat.cpp
  avogadro/qtplugins/fetchpdb/fetchpdb.cpp
Labels: bug

#1134 If the file is empty, return early
  avogadro/io/cjsonformat.cpp
Labels: bug

#1135 Screen space shading
  avogadro/qtopengl/CMakeLists.txt
  avogadro/qtopengl/glwidget.cpp
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/bondcentrictool/CMakeLists.txt
  avogadro/qtplugins/coloropacitymap/CMakeLists.txt
  avogadro/qtplugins/coloropacitymap/histogramwidget.cpp
  avogadro/qtplugins/editor/CMakeLists.txt
  avogadro/qtplugins/label/CMakeLists.txt
  avogadro/qtplugins/manipulator/CMakeLists.txt
  avogadro/qtplugins/measuretool/CMakeLists.txt
  avogadro/qtplugins/meshes/meshes.cpp
  avogadro/qtplugins/navigator/CMakeLists.txt
  avogadro/qtplugins/resetview/CMakeLists.txt
  avogadro/qtplugins/selectiontool/CMakeLists.txt
  avogadro/qtplugins/surfaces/CMakeLists.txt
  avogadro/qtplugins/svg/CMakeLists.txt
  avogadro/qtplugins/templatetool/CMakeLists.txt
  avogadro/rendering/CMakeLists.txt
  avogadro/rendering/avogadrorendering.h
  avogadro/rendering/curvegeometry.cpp
  avogadro/rendering/cylindergeometry.cpp
  avogadro/rendering/glrenderer.cpp
  avogadro/rendering/glrenderer.h
  avogadro/rendering/solid_first_fs.glsl
  avogadro/rendering/solid_vs.glsl
  avogadro/rendering/solidpipeline.cpp
  avogadro/rendering/solidpipeline.h
  avogadro/rendering/spheregeometry.cpp
  avogadro/vtk/vtkglwidget.h
Labels: enhancement, rendering

#1136 Fix bug with "combined rows" like Theory / Basis set
  avogadro/qtgui/jsonwidget.cpp
Labels: bug

#1141 By default only enable regular cartoons
  avogadro/qtplugins/cartoons/cartoons.cpp
Labels: rendering

#1142 Turn off deprecated declarations (e.g., Qt 5.15)
  avogadro/CMakeLists.txt
Labels: build

#1146 Fix rendering bug that dropped half of the MO rendering
  avogadro/qtplugins/meshes/meshes.cpp
  avogadro/qtplugins/surfaces/surfaces.cpp
Labels: bug, rendering

#1133 Fix mis-translated export dialog
  avogadro/qtgui/fileformatdialog.cpp
Labels: bug

#1148 Mitigate bright edges in SSAO
  avogadro/rendering/solid_first_fs.glsl
Labels: bug

#1152 Make sure to cache icons for the LayerModel
  avogadro/qtgui/layermodel.cpp
  avogadro/qtgui/layermodel.h
Labels: speed

#1157 Fix editor smooth drag
  avogadro/qtplugins/editor/editor.cpp
Labels: bug, speed

#1158 Fix requests to the NIH resolver to use new scheme
  avogadro/qtplugins/networkdatabases/networkdatabases.cpp
Labels: bug

#1140 Tweak the edge detection to allow changing the strength too
  avogadro/rendering/solid_first_fs.glsl
  avogadro/rendering/solidpipeline.cpp
  avogadro/rendering/solidpipeline.h
Labels: rendering
