Repository OpenChemistry/avogadrolibs, pull requests merged in 2023-12, with the labels that each got.

#1499 Fix potential crashes in selection commands
  avogadro/qtplugins/select/select.cpp
Labels: bug, crash

#1504 Fix include of avogadrocoreexport.h
  avogadro/core/atomutilities.h
  avogadro/core/coordinateblockgenerator.h
Labels: build

#1508 Make sure to automatically load the "Meshes" display type
  avogadro/qtplugins/surfaces/surfacedialog.cpp
  avogadro/qtplugins/surfaces/surfacedialog.ui
  avogadro/qtplugins/surfaces/surfaces.cpp
Labels: bug

#1506 Add initial support for copy from tables
  avogadro/qtplugins/propertytables/propertyview.cpp
  avogadro/qtplugins/propertytables/propertyview.h
Labels: enhancement

#1509 Turn off Color Opacity Map unless a VTK widget is active
  avogadro/qtplugins/coloropacitymap/coloropacitymap.cpp
  avogadro/qtplugins/coloropacitymap/coloropacitymap.h
Labels: bug

#1515 Added copy and export feature to property tables
  avogadro/qtplugins/propertytables/propertyview.cpp
  avogadro/qtplugins/propertytables/propertyview.h
Labels: enhancement

#1517 Fix two minor ... for translations
  avogadro/qtplugins/propertytables/propertyview.cpp
  avogadro/qtplugins/templatetool/templatetoolwidget.ui
Labels: i18n

#1523 Fix for first item in ordered plugin dialog being empty
  avogadro/qtgui/jsonwidget.cpp
Labels: bug

#1526 Fix crash in forcefields - check if method is valid before using it
  avogadro/qtplugins/forcefield/forcefield.cpp
Labels: bug

#1429 Vibrational spectra plot
  avogadro/core/molecule.cpp
  avogadro/core/molecule.h
  avogadro/io/cjsonformat.cpp
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/spectra/CMakeLists.txt
  avogadro/qtplugins/spectra/spectra.cpp
  avogadro/qtplugins/spectra/spectra.h
  avogadro/qtplugins/spectra/spectradialog.cpp
  avogadro/qtplugins/spectra/spectradialog.h
  avogadro/qtplugins/spectra/spectradialog.ui
  avogadro/qtplugins/templatetool/CMakeLists.txt
  avogadro/qtplugins/vibrations/CMakeLists.txt
  avogadro/qtplugins/vibrations/vibrationdialog.cpp
  avogadro/qtplugins/vibrations/vibrationdialog.h
  avogadro/qtplugins/vibrations/vibrationdialog.ui
  avogadro/qtplugins/vibrations/vibrationmodel.cpp
  avogadro/qtplugins/vibrations/vibrationmodel.h
  avogadro/qtplugins/vibrations/vibrations.cpp
  avogadro/qtplugins/vibrations/vibrations.h
  avogadro/vtk/chartwidget.cpp
  avogadro/vtk/chartwidget.h
Labels: enhancement

#1533 Upgrading to upload / download v4 broke wheel builds
  .github/workflows/build_wheels.yml
Labels: build

#1537 Fix density color crash
  avogadro/qtplugins/meshes/meshes.cpp
  avogadro/qtplugins/propertytables/propertyview.h
  avogadro/qtplugins/spacegroup/spacegroup.h
  avogadro/qtplugins/surfaces/surfacedialog.cpp
  avogadro/qtplugins/surfaces/surfaces.cpp
Labels: bug, crash

#1542 Add red = a, blue = b, green = c color axes for unit cells
  avogadro/qtplugins/crystal/crystalscene.cpp
  avogadro/qtplugins/crystal/crystalscene.h
  avogadro/rendering/linestripgeometry.cpp
  avogadro/rendering/linestripgeometry.h
Labels: enhancement

#1546 Update to cibuildwheel for Python 3.12
  .github/workflows/build_wheels.yml
Labels: build

#1547 Add Qt6 build tests again
  .github/workflows/build_qt6.yml
  avogadro/qtgui/insertfragmentdialog.cpp
  avogadro/qtgui/insertfragmentdialog.h
  avogadro/qtgui/sortfiltertreeproxymodel.cpp
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/aligntool/aligntool.cpp
  avogadro/qtplugins/forcefield/forcefield.cpp
  avogadro/qtplugins/openbabel/conformersearchdialog.cpp
  avogadro/qtplugins/openbabel/conformersearchdialog.h
Labels: build

#1551 Skip calculating points too far apart (e.g., negligible)
  avogadro/core/gaussiansettools.cpp
  avogadro/core/gaussiansettools.h
Labels: speed

#1427 Add some additional classes including cjson and connect
  python/CMakeLists.txt
  python/avogadro/__init__.py
  python/avogadro/cjson.py
  python/avogadro/connect.py
  python/io.cpp
Labels: python

#1555 Improved python configure dialog
  avogadro/qtgui/filebrowsewidget.cpp
  avogadro/qtgui/filebrowsewidget.h
  avogadro/qtgui/utilities.cpp
  avogadro/qtgui/utilities.h
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/configurepython/CMakeLists.txt
  avogadro/qtplugins/configurepython/configurepython.cpp
  avogadro/qtplugins/configurepython/configurepython.h
  avogadro/qtplugins/configurepython/configurepythondialog.cpp
  avogadro/qtplugins/configurepython/configurepythondialog.h
  avogadro/qtplugins/configurepython/configurepythondialog.ui
  avogadro/qtplugins/plugindownloader/plugindownloader.cpp
  avogadro/qtplugins/plugindownloader/plugindownloader.h
  avogadro/qtplugins/quantuminput/quantuminput.cpp
  avogadro/qtplugins/quantuminput/quantuminput.h
Labels: python
