Repository OpenChemistry/avogadrolibs, pull requests merged in 2023-10, with the labels that each got.

#1359 Re-enable CML fragments in case someone has old files
  avogadro/qtplugins/insertfragment/insertfragmentdialog.cpp
Labels: bug

#1364 Initial port of align tool from Avogadro 1.x code
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/aligntool/CMakeLists.txt
  avogadro/qtplugins/aligntool/align.png
  avogadro/qtplugins/aligntool/align@2x.png
  avogadro/qtplugins/aligntool/aligntool.cpp
  avogadro/qtplugins/aligntool/aligntool.h
  avogadro/qtplugins/aligntool/aligntool.qrc
Labels: enhancement

#1367 Validating filenames before opening files for read / write
  avogadro/io/fileformat.cpp
  avogadro/io/fileformat.h
  avogadro/qtgui/fileformatdialog.cpp
Labels: bug

#1374 Add initial crystal and space group commands, including fillUnitCell
  avogadro/qtplugins/crystal/crystal.cpp
  avogadro/qtplugins/crystal/crystal.h
  avogadro/qtplugins/spacegroup/spacegroup.cpp
  avogadro/qtplugins/spacegroup/spacegroup.h
Labels: enhancement

#1380 Reading Gaussian fchk vibrations when present
  avogadro/quantumio/gaussianfchk.cpp
  avogadro/quantumio/gaussianfchk.h
Labels: enhancement

#1406 Fix spurious "change layer" bug with the selection tool
  avogadro/qtplugins/selectiontool/selectiontoolwidget.cpp
Labels: bug, crash

#1410 Add command script path to just select atoms
  avogadro/qtgui/interfacescript.cpp
Labels: enhancement

#1413 Fix Python module install dir
  python/CMakeLists.txt
Labels: python

#1412 vtk: Add missing OpenGL link target
  avogadro/vtk/CMakeLists.txt
Labels: build

#1418 Add workflow concurrency - should stop builds during quick changes
  .github/workflows/build_cmake.yml
  .github/workflows/build_m1.yml
  .github/workflows/build_wheels.yml
  .github/workflows/codacy.yml
  .github/workflows/codeql.yml
Labels: build

#1423 Make sure that filename validation occurs on save, not open
  avogadro/io/fileformat.cpp
  avogadro/qtgui/fileformatdialog.cpp
Labels: bug

#1422 Parsing orca output would crash when swapping orbitals
  avogadro/quantumio/orca.cpp
  avogadro/quantumio/orca.h
Labels: bug

#1433 Revert validation of filenames.
  avogadro/io/fileformat.cpp
  avogadro/qtgui/fileformatdialog.cpp
Labels: bug
