Repository OpenChemistry/avogadrolibs, pull requests merged in 2023-04, with the labels that each got.

#1229 Fix atom index labels to start with 1, not zero as users expect
  avogadro/qtplugins/label/label.cpp
Labels: bug

#1230 When removing an atom, remove bonded hydrogens if needed
  avogadro/qtplugins/editor/editor.cpp
Labels: bug

#1235 Translations update from Hosted Weblate
  i18n/af.po
  i18n/ar.po
  i18n/bg.po
  i18n/bs.po
  i18n/ca.po
  i18n/ca@valencia.po
  i18n/cs.po
  i18n/da.po
  i18n/de.po
  i18n/el.po
  i18n/en_AU.po
  i18n/en_CA.po
  i18n/en_GB.po
  i18n/eo.po
  i18n/es.po
  i18n/et.po
  i18n/eu.po
  i18n/fa.po
  i18n/fi.po
  i18n/fr.po
  i18n/fr_CA.po
  i18n/gl.po
  i18n/he.po
  i18n/hi.po
  i18n/hr.po
  i18n/hu.po
  i18n/id.po
  i18n/it.po
  i18n/ja.po
  i18n/ka.po
  i18n/kn.po
  i18n/ko.po
  i18n/ms.po
  i18n/nb.po
  i18n/nl.po
  i18n/oc.po
  i18n/pl.po
  i18n/pt.po
  i18n/pt_BR.po
  i18n/ro.po
  i18n/ru.po
  i18n/sa.po
  i18n/sk.po
  i18n/sl.po
  i18n/sq.po
  i18n/sr.po
  i18n/sv.po
  i18n/ta.po
  i18n/te.po
  i18n/th.po
  i18n/tr.po
  i18n/ug.po
  i18n/uk.po
  i18n/vi.po
  i18n/zh_CN.po
  i18n/zh_TW.po
Labels: i18n

#1236 When deleting an atom, adjust the hydrogens of the neighbors
  avogadro/qtplugins/editor/editor.cpp
Labels: bug

#1215 Another try at a CodeQL scanning workflow
  .github/workflows/codeql.yml
Labels: build

#1232 Update CMake builds to re-enable Win / Mac VTK and use newer VM
  .github/workflows/build_cmake.yml
  .github/workflows/build_m1.yml
  avogadro/vtk/chartwidget.h
Labels: build

#1243 Fix base64 syntax for signing certificate on Mac
  .github/workflows/build_m1.yml
Labels: build

#1244 Allow continue-on-error for notarization
  .github/workflows/build_m1.yml
Labels: build

#1245 Try running analysis with newer Qt5 version
  .github/workflows/clang-tidy.yml
Labels: build

#1251 Ignore false positives from overflow multiplication
  .github/codeql-config.yml
  .github/workflows/codeql.yml
Labels: build

#1276 Update GAMESS coordinates to store the final version
  avogadro/quantumio/gamessus.cpp
Labels: bug, file-format

#1283 Temporarily disable Codacy scan
  .github/workflows/codacy.yml
Labels: build

#1281 Add arm64 Python wheel builds for Mac
  .github/workflows/build_wheels.yml
Labels: build, python
