Repository OpenChemistry/avogadrolibs, pull requests merged in 2024-10, with the labels that each got.

#1662 Add depth-of-field (Blurring rendering options)
  avogadro/rendering/CMakeLists.txt
  avogadro/rendering/solid_first_fs.glsl
  avogadro/rendering/solidpipeline.cpp
  avogadro/rendering/solidpipeline.h
Labels: rendering

#1728 Turn off default depth blur, shadows, edge for speed
  avogadro/rendering/solidpipeline.cpp
Labels: rendering, speed

#1732 Add initial support for reading molden frequencies
  avogadro/quantumio/molden.cpp
  avogadro/quantumio/molden.h
Labels: enhancement, file-format

#1736 Add BABEL_LIBDIR and BABEL_DATADIR to environment on Mac
  avogadro/qtplugins/forcefield/obenergy.cpp
Labels: bug

#1735 Initial support for reading charges and forces from extended XYZ
  avogadro/io/xyzformat.cpp
Labels: enhancement, file-format

#1742 Prevent a possible unhandled exception from parsing JSON
  avogadro/qtplugins/plugindownloader/downloaderwidget.cpp
Labels: bug, crash

#1746 ENH: Additional Secondary Structures
  avogadro/core/secondarystructure.cpp
  avogadro/rendering/cartoongeometry.cpp
Labels: enhancement
