Repository OpenChemistry/avogadrolibs, pull requests merged in 2024-01, with the labels that each got.

#1566 Fixed crash with angle properties on an empty molecule
  avogadro/core/graph.cpp
Labels: bug, crash

#1562 Add support for first launch dialog and conda environments
  avogadro/qtplugins/configurepython/CMakeLists.txt
  avogadro/qtplugins/configurepython/condadialog.cpp
  avogadro/qtplugins/configurepython/condadialog.h
  avogadro/qtplugins/configurepython/condadialog.ui
  avogadro/qtplugins/configurepython/configurepython.cpp
  avogadro/qtplugins/configurepython/configurepython.h
  avogadro/qtplugins/configurepython/configurepythondialog.cpp
  avogadro/qtplugins/configurepython/configurepythondialog.h
Labels: enhancement

#1559 Add confirmation dialog to install with conda or pip
  avogadro/qtplugins/plugindownloader/downloaderwidget.cpp
  avogadro/qtplugins/plugindownloader/downloaderwidget.h
Labels: enhancement, python

#1576 Modern tool icons
  avogadro/qtplugins/aligntool/align_dark.svg
  avogadro/qtplugins/aligntool/align_light.svg
  avogadro/qtplugins/aligntool/aligntool.cpp
  avogadro/qtplugins/aligntool/aligntool.qrc
  avogadro/qtplugins/bondcentrictool/bondcentric_dark.svg
  avogadro/qtplugins/bondcentrictool/bondcentric_light.svg
  avogadro/qtplugins/bondcentrictool/bondcentrictool.cpp
  avogadro/qtplugins/bondcentrictool/bondcentrictool.qrc
  avogadro/qtplugins/editor/editor.cpp
  avogadro/qtplugins/editor/editor.qrc
  avogadro/qtplugins/editor/editor_dark.svg
  avogadro/qtplugins/editor/editor_light.svg
  avogadro/qtplugins/label/label.qrc
  avogadro/qtplugins/label/label_dark.svg
  avogadro/qtplugins/label/label_light.svg
  avogadro/qtplugins/label/labeleditor.cpp
  avogadro/qtplugins/manipulator/manipulator.cpp
  avogadro/qtplugins/manipulator/manipulator.qrc
  avogadro/qtplugins/manipulator/manipulator_dark.svg
  avogadro/qtplugins/manipulator/manipulator_light.svg
  avogadro/qtplugins/measuretool/measure_dark.svg
  avogadro/qtplugins/measuretool/measure_light.svg
  avogadro/qtplugins/measuretool/measuretool.cpp
  avogadro/qtplugins/measuretool/measuretool.qrc
  avogadro/qtplugins/navigator/navigator.cpp
  avogadro/qtplugins/navigator/navigator.qrc
  avogadro/qtplugins/navigator/navigator_dark.svg
  avogadro/qtplugins/navigator/navigator_light.svg
  avogadro/qtplugins/playertool/player_dark.svg
  avogadro/qtplugins/playertool/player_light.svg
  avogadro/qtplugins/playertool/playertool.cpp
  avogadro/qtplugins/playertool/playertool.qrc
  avogadro/qtplugins/selectiontool/selection_dark.svg
  avogadro/qtplugins/selectiontool/selection_light.svg
  avogadro/qtplugins/selectiontool/selectiontool.cpp
  avogadro/qtplugins/selectiontool/selectiontool.qrc
  avogadro/qtplugins/templatetool/template.qrc
  avogadro/qtplugins/templatetool/template_dark.svg
  avogadro/qtplugins/templatetool/template_light.svg
  avogadro/qtplugins/templatetool/templatetool.cpp
Labels: enhancement

#1578 Update tool plugins to set icon as light / dark theme
  avogadro/qtgui/toolplugin.h
  avogadro/qtplugins/aligntool/aligntool.cpp
  avogadro/qtplugins/aligntool/aligntool.h
  avogadro/qtplugins/bondcentrictool/bondcentrictool.cpp
  avogadro/qtplugins/bondcentrictool/bondcentrictool.h
  avogadro/qtplugins/editor/editor.cpp
  avogadro/qtplugins/editor/editor.h
  avogadro/qtplugins/label/labeleditor.cpp
  avogadro/qtplugins/label/labeleditor.h
  avogadro/qtplugins/manipulator/manipulator.cpp
  avogadro/qtplugins/manipulator/manipulator.h
  avogadro/qtplugins/measuretool/measuretool.cpp
  avogadro/qtplugins/measuretool/measuretool.h
  avogadro/qtplugins/navigator/navigator.cpp
  avogadro/qtplugins/navigator/navigator.h
  avogadro/qtplugins/playertool/playertool.cpp
  avogadro/qtplugins/playertool/playertool.h
  avogadro/qtplugins/selectiontool/selectiontool.cpp
  avogadro/qtplugins/selectiontool/selectiontool.h
  avogadro/qtplugins/templatetool/templatetool.cpp
  avogadro/qtplugins/templatetool/templatetool.h
Labels: enhancement
