Repository OpenChemistry/avogadrolibs, pull requests merged in 2024-02, with the labels that each got.

#1588 Fix bug with incorrect Unicode characters added to labels
  avogadro/qtgui/extensionplugin.h
  avogadro/qtgui/toolplugin.h
  avogadro/qtplugins/label/labeleditor.cpp
Labels: bug

#1591 Add an optional calculator that links Open Babel
  avogadro/calc/energymanager.cpp
  avogadro/qtplugins/forcefield/CMakeLists.txt
  avogadro/qtplugins/forcefield/forcefield.cpp
  avogadro/qtplugins/forcefield/obenergy.cpp
  avogadro/qtplugins/forcefield/obenergy.h
  cmake/FindOpenBabel3.cmake
Labels: enhancement

#1604 Adapt build from avogadroapp to include OpenSSL dll for Windows
  .github/workflows/build_cmake.yml
Labels: build

#1612 Fix wrong variable name
  avogadro/qtplugins/templatetool/CMakeLists.txt
Labels: build

#1621 Fix crash at startup when opening a file from commandline
  avogadro/qtgui/sceneplugin.h
  avogadro/qtgui/scenepluginmodel.cpp
  avogadro/qtplugins/ballandstick/ballandstick.h
  avogadro/qtplugins/cartoons/cartoons.h
  avogadro/qtplugins/closecontacts/closecontacts.h
  avogadro/qtplugins/crystal/crystalscene.h
  avogadro/qtplugins/label/label.h
  avogadro/qtplugins/meshes/meshes.h
  avogadro/qtplugins/noncovalent/noncovalent.h
  avogadro/qtplugins/wireframe/wireframe.h
Labels: crash

#1624 Fix crash from centroids with empty molecule
  avogadro/qtplugins/centroid/centroid.cpp
Labels: crash

#1625 Fixed Select Bugs from forum
  avogadro/qtplugins/select/select.cpp
Labels: crash

#1585 Cmake: Remove custom `Find<Package>.cmake` modules
  CMakeLists.txt
  avogadro/core/CMakeLists.txt
  cmake/FindEigen3.cmake
  cmake/FindSPGLIB.cmake
Labels: build
