Repository OpenChemistry/avogadrolibs, pull requests merged in 2025-03, with the labels that each got.

#1977 style(i18n): add --check=ellipsis-unicode for gettext and use unicode ellipsis
  avogadro/qtplugins/apbs/apbsdialog.ui
  avogadro/qtplugins/spectra/spectradialog.ui
  scripts/extract-messages.sh
Labels: i18n

#1976 build: replace FindPythonInterp with FindPython3
  avogadro/qtgui/CMakeLists.txt
  tests/qtgui/CMakeLists.txt
Labels: build

#1983 Fix translucent surface culling
  avogadro/qtplugins/surfaces/surfaces.cpp
  avogadro/rendering/glrenderer.cpp
Labels: bug, rendering
