Repository OpenChemistry/avogadrolibs, pull requests merged in 2025-07, with the labels that each got.

#2078 fix: fix test suite names
  tests/core/CMakeLists.txt
  tests/core/atomtypertest.cpp
Labels: build

#2080 fix(wrapFractional): fix comparison
  avogadro/core/unitcell.h
Labels: bug

#2079 fix override specification
  avogadro/calc/defaultmodel.h
  avogadro/calc/energycalculator.h
  avogadro/calc/lennardjones.h
  avogadro/calc/uff.h
  avogadro/core/coordinateset.h
  avogadro/molequeue/client/client.h
  avogadro/molequeue/client/jsonrpcclient.h
  avogadro/qtgui/backgroundfileformat.h
  avogadro/qtgui/colorbutton.h
  avogadro/qtgui/sortfiltertreeproxymodel.h
  avogadro/qtgui/toolplugin.h
  avogadro/qtplugins/cp2kinput/cp2kinput.h
  avogadro/qtplugins/cp2kinput/cp2kinputdialog.h
  avogadro/qtplugins/lammpsinput/lammpsinputdialog.h
  avogadro/qtplugins/molecularproperties/molecularmodel.h
  avogadro/qtplugins/openbabel/conformersearchdialog.h
  avogadro/qtplugins/openbabel/obcharges.h
  avogadro/qtplugins/openmminput/openmminputdialog.h
  avogadro/qtplugins/plotpdf/pdfoptionsdialog.h
  avogadro/qtplugins/plotpdf/plotpdf.h
  avogadro/qtplugins/plotrmsd/plotrmsd.h
  avogadro/qtplugins/plotxrd/plotxrd.h
  avogadro/qtplugins/plotxrd/xrdoptionsdialog.h
  avogadro/qtplugins/propertytables/propertymodel.h
  avogadro/qtplugins/selectiontool/selectiontoolwidget.h
  avogadro/qtplugins/spacegroup/spacegroup.h
  avogadro/qtplugins/spectra/spectradialog.h
  avogadro/qtplugins/surfaces/orbitals.h
  avogadro/qtplugins/surfaces/orbitaltablemodel.h
  avogadro/qtplugins/surfaces/orbitalwidget.h
  avogadro/qtplugins/surfaces/surfaces.h
  avogadro/qtplugins/templatetool/templatetool.h
  avogadro/qtplugins/templatetool/templatetoolwidget.h
  avogadro/qtplugins/yaehmop/banddialog.h
  avogadro/qtplugins/yaehmop/yaehmop.h
  avogadro/rendering/arrowgeometry.h
  cmake/avogadroplugin.cpp.in
  tests/core/atomtypertest.cpp
Labels: build

#2045 Tweaks to parse ORCA 6.1 output
  avogadro/quantumio/orca.cpp
Labels: file-format

#2093 chore(input): reduce singleStep
  avogadro/qtplugins/cp2kinput/cp2kinputdialog.ui
  avogadro/qtplugins/gamessinput/gamessinputdialog.ui
Labels: file-format

#2097 i18n: resolve conflict with weblate
  i18n/ka.po
Labels: i18n

#2105 Merge with weblate to resolve conflicts
  i18n/bg.po
  i18n/bs.po
  i18n/ca.po
  i18n/ca@valencia.po
  i18n/cs.po
  i18n/da.po
  i18n/de.po
  i18n/el.po
  i18n/et.po
  i18n/eu.po
  i18n/gl.po
  i18n/id.po
  i18n/it.po
  i18n/ja.po
  i18n/ka.po
  i18n/ms.po
  i18n/nl.po
  i18n/pl.po
  i18n/pt.po
  i18n/pt_BR.po
  i18n/ru.po
  i18n/sk.po
  i18n/sl.po
  i18n/sr.po
  i18n/vi.po
  i18n/zh_CN.po
  i18n/zh_TW.po
Labels: i18n

#2096 Add constraints for geometry optimization
  avogadro/calc/CMakeLists.txt
  avogadro/calc/energycalculator.cpp
  avogadro/calc/energycalculator.h
  avogadro/calc/gradients.h
  avogadro/calc/lennardjones.cpp
  avogadro/calc/uff.cpp
  avogadro/core/CMakeLists.txt
  avogadro/core/constraint.h
  avogadro/core/molecule.cpp
  avogadro/core/molecule.h
  avogadro/qtgui/extensionplugin.cpp
  avogadro/qtgui/molecule.h
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/constraints/CMakeLists.txt
  avogadro/qtplugins/constraints/constraintsdialog.cpp
  avogadro/qtplugins/constraints/constraintsdialog.h
  avogadro/qtplugins/constraints/constraintsdialog.ui
  avogadro/qtplugins/constraints/constraintsextension.cpp
  avogadro/qtplugins/constraints/constraintsextension.h
  avogadro/qtplugins/constraints/constraintsmodel.cpp
  avogadro/qtplugins/constraints/constraintsmodel.h
  avogadro/qtplugins/forcefield/forcefield.cpp
  avogadro/qtplugins/forcefield/forcefield.h
  avogadro/qtplugins/forcefield/obenergy.cpp
  avogadro/qtplugins/forcefield/obmmenergy.cpp
  avogadro/qtplugins/forcefield/scriptenergy.cpp
Labels: enhancement
