Repository OpenChemistry/avogadrolibs, pull requests merged in 2025-06, with the labels that each got.

#2016 Fix bug with manual rotations around axes
  avogadro/qtplugins/manipulator/manipulator.cpp
  avogadro/qtplugins/manipulator/manipulator.h
Labels: bug

#1963 Add an internal implementation of UFF
  avogadro/calc/CMakeLists.txt
  avogadro/calc/energymanager.cpp
  avogadro/calc/uff.cpp
  avogadro/calc/uff.h
  avogadro/calc/uffdata.h
  avogadro/core/angleiterator.cpp
  avogadro/core/angleiterator.h
  avogadro/core/angletools.h
  avogadro/core/dihedraliterator.cpp
  avogadro/core/dihedraliterator.h
  avogadro/core/molecule.h
  avogadro/qtplugins/forcefield/forcefield.cpp
  avogadro/qtplugins/propertytables/propertymodel.cpp
Labels: enhancement

#2022 build: bump cmake_minimum_required
  python/CMakeLists.txt
  thirdparty/tinycolormap/CMakeLists.txt
Labels: build

#2026 Update find_dependency calls for Qt6
  cmake/AvogadroLibsConfig.cmake.in
Labels: build

#2028 Update the molecule UI list to include richtext formulas
  avogadro/qtgui/molecule.cpp
  avogadro/qtgui/molecule.h
  avogadro/qtgui/moleculemodel.cpp
  avogadro/qtplugins/molecularproperties/molecularmodel.cpp
Labels: enhancement

#2030 test: enable spacegrouptest only if USE_SPGLIB is true
  tests/core/CMakeLists.txt
Labels: build

#2052 Make sure to save label options for atoms, bonds and residues
  avogadro/core/CMakeLists.txt
  avogadro/core/contrastcolor.h
  avogadro/qtplugins/aligntool/aligntool.cpp
  avogadro/qtplugins/aligntool/aligntool.h
  avogadro/qtplugins/editor/editor.cpp
  avogadro/qtplugins/label/label.cpp
  avogadro/qtplugins/measuretool/measuretool.cpp
  avogadro/qtplugins/measuretool/measuretool.h
Labels: bug

#2054 Use system eigen when building for Linux (inc. AppImage)
  .github/workflows/build_linux.yml
Labels: build

#2059 Fix ODR violations, move enums into class scope
  avogadro/qtplugins/cp2kinput/cp2kinputdialog.cpp
  avogadro/qtplugins/cp2kinput/cp2kinputdialog.h
Labels: build

#2068 fix(cjson): fix properties parsing
  avogadro/io/cjsonformat.cpp
Labels: bug

#2070 Fix crash on Linux when deleting non-hydrogen atoms
  avogadro/qtplugins/editor/editor.cpp
Labels: bug, crash

#2067 improve cp2kinput
  avogadro/qtplugins/cp2kinput/cp2kinputdialog.cpp
  avogadro/qtplugins/cp2kinput/cp2kinputdialog.h
Labels: enhancement

#2072 Fix a bug when changing the bond order atoms wouldn't move properly
  avogadro/qtplugins/editor/editor.cpp
Labels: bug
