Repository OpenChemistry/avogadrolibs, pull requests merged in 2025-05, with the labels that each got.

#1995 Add support for "allxyz" from Orca - trajectory files
  avogadro/io/xyzformat.cpp
Labels: file-format

#1986 adding more options to the gamess input file generator
  avogadro/qtplugins/gamessinput/gamessinputdialog.cpp
  avogadro/qtplugins/gamessinput/gamessinputdialog.h
  avogadro/qtplugins/gamessinput/gamessinputdialog.ui
Labels: enhancement

#2001 Fix reading Chemeleon exyz files with no quotes around the Lattice
  avogadro/io/xyzformat.cpp
Labels: file-format

#2000 Fix reading Gaussian cube - make sure to set origin correctly
  avogadro/quantumio/gaussiancube.cpp
Labels: bug

#2011 When clicking to change an element, tweak the bond length too
  avogadro/qtplugins/editor/editor.cpp
Labels: enhancement
