Repository OpenChemistry/avogadrolibs, pull requests merged in 2025-01, with the labels that each got.

#1914 [skip ci] Fix the geometry of the ethylene ligand
  avogadro/qtplugins/templatetool/ligands/eta2-ethylene.cjson
Labels: build

#1916 Fix code for haptic ligands. Pick the furthest dummy to attach
  avogadro/qtplugins/templatetool/templatetool.cpp
Labels: bug

#1923 Since Qt tests are currently Qt5-only don't build them for Qt6
  tests/CMakeLists.txt
Labels: build

#1928 Avoid crash in orbitals when switching molecules
  avogadro/qtplugins/quantuminput/CMakeLists.txt
  avogadro/qtplugins/surfaces/orbitals.cpp
Labels: bug, crash

#1937 Fix plugin menu entry behaviour
  avogadro/qtgui/scriptloader.cpp
Labels: bug

#1935 Tweak search for Python paths - make sure to check it exists
  avogadro/qtplugins/configurepython/configurepython.cpp
Labels: bug

#1942 Handle SDF data blocks better, including from QupKake
  avogadro/io/mdlformat.cpp
  avogadro/qtplugins/label/label.cpp
Labels: enhancement

#1927 Add some initial fuzz IO tests
  tests/io/CMakeLists.txt
  tests/io/fuzztest.cpp
Labels: build

#1946 Only build MoleQueue tests when requested
  tests/qtgui/CMakeLists.txt
Labels: build

#1948 Bump build to 1.100.0 for release
  CMakeLists.txt
  SECURITY.md
Labels: build

#1950 Harden file readers (from fuzz tests)
  avogadro/io/cjsonformat.cpp
  avogadro/io/cmlformat.cpp
  avogadro/io/mdlformat.cpp
  avogadro/io/pdbformat.cpp
  avogadro/io/xyzformat.cpp
  tests/io/fileformatmanagertest.cpp
Labels: bug
