Repository OpenChemistry/avogadrolibs, pull requests merged in 2025-08, with the labels that each got.

#2131 refactor: use hypot
  avogadro/calc/uff.cpp
  avogadro/core/crystaltools.cpp
  avogadro/qtplugins/qtaim/qtaimlsodaintegrator.cpp
  avogadro/qtplugins/qtaim/qtaimmathutilities.cpp
  avogadro/qtplugins/qtaim/qtaimodeintegrator.cpp
  avogadro/qtplugins/svg/svg.cpp
  avogadro/rendering/plyvisitor.cpp
  avogadro/rendering/vrmlvisitor.cpp
Labels: build

#2118 Add constraints to property tables & save with CJSON
  avogadro/core/molecule.cpp
  avogadro/core/molecule.h
  avogadro/core/utilities.h
  avogadro/io/cjsonformat.cpp
  avogadro/io/mdlformat.cpp
  avogadro/qtplugins/propertytables/propertymodel.cpp
  avogadro/qtplugins/propertytables/propertymodel.h
  avogadro/qtplugins/propertytables/propertyview.cpp
  avogadro/qtplugins/propertytables/propertyview.h
Labels: enhancement

#2133 Export mol/sdf with proper header
  avogadro/io/cjsonformat.cpp
  avogadro/io/mdlformat.cpp
Labels: bug

#2154 fix(QtOpenGL): honor QT_VERSION
  tests/qtopengl/CMakeLists.txt
Labels: build

#2169 fix(templatetool): do not localize functional groups
  avogadro/qtplugins/templatetool/template.qrc
  avogadro/qtplugins/templatetool/templatetoolwidget.cpp
  avogadro/qtplugins/templatetool/templatetoolwidget.h
Labels: bug
