Repository OpenChemistry/avogadrolibs, pull requests merged in 2025-09, with the labels that each got.

#2179 Add additional search paths for Python on Windows
  .github/workflows/build_cmake.yml
  avogadro/qtplugins/configurepython/configurepython.cpp
Labels: bug

#2182 Fix possible crashes reading PDB files with few residues
  avogadro/core/secondarystructure.cpp
  avogadro/io/pdbformat.cpp
  tests/io/pdbtest.cpp
Labels: bug, crash

#2192 Re-enable CJSON conformer unit test
  tests/io/cjsontest.cpp
Labels: build

#2193 Try to fix extraction on Windows using tar.gz instead of zip
  .github/workflows/build_cmake.yml
  .github/workflows/build_qt6.yml
  .github/workflows/build_windows.yml
  avogadro/qtplugins/configurepython/configurepython.cpp
  avogadro/qtplugins/configurepython/configurepythondialog.cpp
  avogadro/qtplugins/plugindownloader/downloaderwidget.cpp
Labels: bug

#2202 Try using Windows vcpkg to install Eigen for Python builds
  scripts/github-actions/install.sh
Labels: build

#2201 Add wireframe style for surfaces
  avogadro/qtplugins/CMakeLists.txt
  avogadro/qtplugins/meshes/CMakeLists.txt
  avogadro/qtplugins/meshes/meshes.cpp
  avogadro/qtplugins/surfacerender/CMakeLists.txt
  avogadro/qtplugins/surfacerender/surfacerender.cpp
  avogadro/qtplugins/surfacerender/surfacerender.h
Labels: enhancement

#2203 Use vcpkg to install eigen3 libarchive libxml2 and zlib
  .github/workflows/build_cmake.yml
Labels: build

#2206 Check SMILES and pop up a warning if there's something wrong
  avogadro/qtplugins/lineformatinput/lineformatinput.cpp
Labels: bug

#2209 Create scorecard.yml
  .github/workflows/scorecard.yml
Labels: build

#2212 add Turbomole test and improve parser
  avogadro/core/utilities.h
  avogadro/io/turbomoleformat.cpp
  tests/io/CMakeLists.txt
  tests/io/turbomoletest.cpp
Labels: file-format
